name: Run Bash
on:
  workflow_dispatch:
jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/checkout@v3
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Create Expo App
        run: pnpm dlx create-expo-app@latest MinecraftClicker
      - name: Install Packages
        run: |
          cd MinecraftClicker
          pnpm add -D three @types/three tailwindcss @tailwindcss/cli
          pnpm install
      - name: Reset Project
        run: |
          cd MinecraftClicker
          pnpm run reset-project
      - name: Build Project
        run: |
          cd MinecraftClicker
          pnpm run build
